zeebe-io/zeebe-cluster-testbench

- README.md
**ommitted** changed to *omitted*.
Fixes #34 .
> Typo fix - README.md

- .ci/scripts/distribution/prepare.sh
- Jenkinsfile
- core/chaos-workers/.gitignore
- core/chaos-workers/installDependencies.sh
Run shellcheck for all chaos bash scripts.
Run bash unit tests in jenkins pipeline.
Add a separate stage to verify the shell scripts
Dependencies are installed directly from repository, I tried some hours with debians package manager and the different backport channels etc but had no luck / didn't worked.
closes https://github.com/zeebe-io/zeebe-cluster-testbench/issues/107
> chore(ci): verify chaos scripts

- core/chaos-workers/.gitignore
- core/chaos-workers/handleJob.sh
- core/chaos-workers/handleJobTest.sh
- core/chaos-workers/handlerUtil.sh
- core/chaos-workers/runWorker.sh
I did more a integration test with the simple monitor and a camunda cloud cluster, which I created manually. In the end I was able to run a chaos experiment based on the given payload and complete the job successfully. There were a lot of failed and retried jobs in between :sweat_smile: 
Cleaned up the worker script. I have a local script to run tests against simple monitor.
Fixes some problems in the job handler code.
The runChaosExperiments has returned an positive value, which causes the job worker to fail the job and retry, which we don't want. The generation of the test result hasn't worked 100% correct. If the message contained white spaces it was also splitted in separate entries. Previous we haven't read the input correctly, since we used the wrong function.
> Some improvements to the chaos worker

- core/chaos-workers/handleJobTest.sh
- core/chaos-workers/handlerUtil.sh
Fixes wrong json template.
**Before**:
```json
{
"testResult": "FAILED",
"failureCount": 1,
"failureMessages": [],
"metaData": {
}
}
```
**After**:
```json
{
"testResult": "FAILED",
"testReport": {
"testResult": "FAILED",
"failureCount": 1,
"failureMessages": [],
"metaData": {
}
}
}
```
Ideally we could define the template in one place where java and script clients can take it from.
closes #117
> fix(chaos): use correct json template

- core/chaos-workers/handleJob.sh
- core/chaos-workers/handleJobTest.sh
- core/chaos-workers/handlerUtil.sh
Previous tests have been failed because there were not experiments for development, production s etc in the github repo. In order to prevent that we check now whether files exist. If there are no experiments to execute the test is passed.
> chore(chaos): dont fail test if files not exist

- core/chaos-workers/handleJob.sh
Deploys now in the job handler the necessary job workers which we can find here now https://github.com/zeebe-io/zeebe-chaos/blob/master/chaos-experiments/camunda-cloud/worker.yaml
> Deploy workers in job handler

- .ci/scripts/deploy.sh
- .editorconfig
- .gitignore
- Jenkinsfile
- core/chaos-workers/chaosWorker-dev.yaml
- testbench-dev.yaml
closes #100 
This adds a build parameter "DEPLOY_TO_DEV"
When this is set:
* the image will be tagged with `:dev`
* all artifacts will be deployed into the namespace `testbench-dev`
* for all artifacts the deployment descriptor `...-dev.yaml` will be used
When this is not set and we are on the master, it will continue deploy the `:latest` image to `testbench` namespace as usual.
Enabling "DEPLOY_TO_DEV" on master is also possible and will deploy to dev. One use case of this could be to overwrite a bad deployment on dev.
> chore(ci): add optional deployment to dev stage

- core/chaos-workers/handlerUtil.sh
Previous the `chaostoolkit.log` was not stored in the pvc only the output of chaostoolkit.
> Store chaostoolkit.log in pvc

- .ci/scripts/deploy.sh
- core/chaos-workers/deployment/chaos-data-claim.yaml
- core/chaos-workers/deployment/chaosWorker-dev.yaml
- core/chaos-workers/deployment/chaosWorker.yaml
* Moves the chaos worker deployments in new subfolder.
* Extracts pvc in own file.
*  Adjust chaos worker dev deployment.
* changes rollout strategy to recreate. Default is rolling update which is problematic with the pvc, because can only attached once.
> fix(chaos): fix chaos worker deployment

- core/chaos-workers/handleJob.sh
- core/chaos-workers/runChaos.sh
Uses the runChaos script to be more resistant against changes in the zeebe-chaos repo.
Previous it assumed a structure of the repo which might change as we did with zeebe-io/zeebe-chaos#44
> chore(chaos): use runChaos script

- core/chaos-workers/runWorker.sh
Configures the chaos worker:
* activates one job at a time
* sets concurrency to 1
* sets timeout to 1 hour
> chore(chaos): configure chaos worker

- core/chaos-workers/runWorker.sh
I mistakenly added yesterday the insecure flag this is the reason why currently the worker doesnt connect :see_no_evil: sorry.
> fix(chaos): remove insecure flag

- workflows/daily-test-protocol.bpmn
- workflows/qa-protocol.bpmn
Adds a new variable `rootWorkflow` to the root workflows. The expectation is that this variable will be inherited to the processes called from the root workflow. This should make it easier in Operate to know which test came from where.
closes #125
> chore(workflows): add root workflow information

- cloud-client/src/main/java/io/zeebe/clustertestbench/cloud/CloudAPIClientFactory.java
- cloud-client/src/main/java/io/zeebe/clustertestbench/cloud/filter/BadRequestResponseFilter.java
- cloud-client/src/main/java/io/zeebe/clustertestbench/cloud/oauth/OAuthClientFactory.java
- cloud-client/src/main/java/io/zeebe/clustertestbench/cloud/request/CreateZeebeClientRequest.java
- cloud-client/src/main/java/io/zeebe/clustertestbench/cloud/response/ZeebeClientConnectiontInfo.java
- cloud-client/src/test/java/io/zeebe/clustertestbench/cloud/response/ClientConnectiontInfoTest.java
- core/src/main/java/io/zeebe/clustertestbench/handler/CreateClusterInCamundaCloudHandler.java
- internal-cloud-client/src/main/java/io/zeebe/clustertestbench/internal/cloud/InternalCloudAPIClientFactory.java
closes #165 
The changes in the backend were:
* the request to create a client now has a permissions field
* the client secret is only returned as response to the create Zeebe client request
* the old secret returned in the response when asking for information on a client is set to an empty string
Changes in the testbench:
* add permissions to create zeebe client request
* use secret returned from create zeebe client request
* remove obsolete field `secret` from `ZeebeClientConnectionInfo`
* (not related to the bugfix, but necessary to debug what was going on) Add a response filter that throws an exception for _bad request_ responses and copies the request body and response body into the message of the exception
> 165 incorporate backend changes

- core/chaos-workers/installDependencies.sh
Install coreutils package as dependency to have access to nanoseconds to generate correct timestamp (with milliseconds).
Output now before the last 3 numbers were missing
```
[zell chaos-workers/ ns:testbench]$ k exec -it chaos-worker-6c7484c474-jhrg8 --  date +%s%3N
1606397280716
```
closes https://github.com/zeebe-io/zeebe-cluster-testbench/issues/167
> fix(chaos): use other version of date tool

- workflows/run-test-in-camunda-cloud.bpmn
First step towards #122 
(Outdated) This adds an output mapping to the test process to automatically extract the test result from the test report.
Updated: This changes the flow conditions to use the `testResult` inside the `testReport` data, not the top level `testResult` variable
This makes the `testResult` variable obsolete, and then it can be removed from the test processes in later PRs.
> chore(workflows): extract testResult from testReport automatically

- core/src/main/java/io/zeebe/clustertestbench/handler/CreateGenerationInCamundaCloudHandler.java
- core/src/test/java/io/zeebe/clustertestbench/handler/CreateGenerationInCamundaCloudHandlerTest.java
This changes the algorithm for names for generation that are created by the testbench.
Before:
`temp_[image name]_[UUID]` e.g. `temp_gcr.io/zeebe-io/zeebe:0.26.0-SNAPSHOT-3fbe61a3a766b126e146b098ba09509648ff2df7_94853a44-4229-4e5d-abb2-a19723b3956a`
Downsides:
* the name is massive. It looks terrible in the UI 
* the UUID at the end is just so that we can have different generations for the same image (in case different tests are running. Each test is responsible for cleaning up its generation). However, this UUID is not the UUID of the generation (which will be generated after a name has been chosen). So this is confusing and overall a bad idea.
* the image name is also quite long as it contains registry, imagename, version, qualifier and full commit hash. Additionally, it's redundant …
> chore(ci): change algo for generation names

- core/src/main/java/io/zeebe/clustertestbench/handler/RecordTestResultHandler.java
- core/src/test/java/io/zeebe/clustertestbench/handler/RecordTestResultHandlerTest.java
closes #203 
Changes:
- null values in the test report will now be replaced with "n/a" to preserve column layout
> fx(core): replace null values with n/a to prevent misalignment

- .ci/scripts/deploy.sh
- Jenkinsfile
- core/src/main/java/io/zeebe/clustertestbench/bootstrap/BootstrapFromEnvVars.java
- core/src/main/java/io/zeebe/clustertestbench/bootstrap/Launcher.java
- core/src/main/java/io/zeebe/clustertestbench/handler/NotifyEngineersHandler.java
- core/src/main/java/io/zeebe/clustertestbench/notification/SlackNotificationService.java
- docs/operator-handbook.md
- testbench-dev.yaml
- testbench.yaml
**Description**
This PR removes the real-time-messaging Slack integration and replaces it with a simple incoming-webhook usage. See the original issue as to why.
The self test is replaced with a simple request sending an empty payload which should return a specific error. This is somewhat brittle, and welcome to be challenged (not sufficient to check the error code as using a weird URL will still return a 400, just a different error).
Vault has been updated with a new `slackWebhookUrl`, and the docs have also been updated (partially - it seems other parts also need to be updated but were outside of this scope).
**Related issues**
closes #212
> Use Slack incoming-webhooks to post messages

- core/chaos-workers/Dockerfile
We had again the issue that the cloud token was not updated/renewed after the TTL expired. I hope that a newer version of zbctl fixes that. Otherwise I will reopen again some issues in zeebe.
> chore(core): update zbctl

- workflows/chaosToolkit.bpmn
The chaosToolkit process generated the start and end time as string, calculated by string(now()), but the parent process expects an long (milliseconds). This caused an incident on execution.
I was able to find a feel expression to calculate the seconds until epoch (1970-01-01T00:00Z) and multiply it by 1000 to get milliseconds
` =((now() - date and time(1970-01-01T00:00Z)) / duration(PT1S)) * 1000` more accuracy is not supported by feel.
It tried it with the feel runner https://github.com/Zelldon/feel-runner
```
$((now() - date and time("1970-01-01T00:00Z")) / duration("PT1S")) * 1000
Try expression: =((now() - date and time("1970-01-01T00:00Z")) / duration("PT1S")) * 1000
EvaluationResult: io.zeebe.el.impl.feel.FeelEvaluationResult@3e6f3f28
Result type: NUMBER
Result failure: null
Result …
```
> Fix chaos test report

- .github/dependabot.yml
Changes dependabot conifguration:
* will now run daily instead of weekly
* will also run for `stable/0.26`
Fixes: #261
> github(dependabot): Configure Dependabot to run also for stable branch

- core/chaos-workers/Dockerfile
Bumps zeebe version to 1.0.0-alpha4
> Fix chaos worker for Testbench 1.x

- core/chaos-workers/.gitignore
- core/chaos-workers/chaos-worker/src/main/kotlin/io/zeebe/chaos/DeployMultipleVersionsHandler.kt
- core/chaos-workers/chaos-worker/src/main/kotlin/io/zeebe/chaos/chaosMain.kt
- core/chaos-workers/chaos-worker/src/main/resources/log4j2.xml
- core/chaos-workers/deployment/chaosWorker-dev.yaml
- core/chaos-workers/deployment/chaosWorker.yaml
I wanted to replace the [deploy different version](https://github.com/zeebe-io/zeebe-chaos/blob/master/chaos-experiments/scripts/deploy-different-versions.sh) scripts with a kotlin worker, in general it worked and I like the resultat but I had problem to run it.
I get always:
```
18:31:57.681 [grpc-default-executor-4] ERROR Java Client: io.zeebe.client.impl.oauth.OAuthCredentialsProvider - Failed while fetching credentials: 
java.io.IOException: Failed while requesting access token with status code 429 and message Too Many Requests.
at io.zeebe.client.impl.oauth.OAuthCredentialsProvider.fetchCredentials(OAuthCredentialsProvider.java:184) ~[chaosWorker.jar:2.0.0-SNAPSHOT]
at io.zeebe.client.impl.oauth.OAuthCredentialsProvider.refreshCredentials(OAuthCredentialsProvider.java:133) …
```
> Deploy multi version worker

- core/chaos-workers/Dockerfile
- core/chaos-workers/chaos-worker/src/main/kotlin/io/zeebe/chaos/chaosMain.kt
In order to change the zeebe-chaos experiments, to make them 1.x compatible, we need to use in the chaos worker the old experiments (tagged with 0.26.1). In the Testbench 1.x we can then use the newer experiments which are migrated and on the older Testbench the 0.26.1 version.
> Use 0.26.1 tag in Chaos Worker

- scripts/wait-for-result.sh
Zbctl nowaways returns jobs differently. It used to be an array of jobs,
now it is a json object with a `jobs` property that contains the array
of jobs, i.e. instead of `[]`, it's now `{"jobs":[]}`.
closes #194
> fix(script): correct wait-for-result job key parsing

- core/src/main/java/io/zeebe/clustertestbench/bootstrap/Launcher.java
- core/src/main/java/io/zeebe/clustertestbench/handler/WarmUpClusterHandler.java
- testdriver/sequential/src/main/java/io/zeebe/clustertestbench/testdriver/sequential/SequentialTestDriver.java
This will make #308 possible. `brokerContactPoint` was already deprecated for some time, but is removed in `1.0.0-alpha7`. It should be replaced by `gatewayAddress`.
> fix(zeebe): replace deprecated brokerContactPoint

- core/chaos-workers/deployment/chaosWorker-prod.yaml
- testbench-prod.yaml
The switch is made by switching the client-id and by changing the values
in vault.
> Switch to 1.0.0-rc1 cluster

- testdriver/sequential/src/main/java/io/zeebe/clustertestbench/testdriver/sequential/SequentialTestDriver.java
When replacing the external dependency to zeebe-workflow-generator, it
seems the wrong method was called to create the sequential test process.
> fix(testdriver): make sequential process executable

- core/chaos-workers/deployment/chaosWorker-dev.yaml
- testbench-dev.yaml
The vault secrets have already been updated.
This just updates the client id to align with those configurations set by the vault secrets.
> Switch dev cluster to testbench-1.x-dev

- .github/workflows/backport.yml
Adds a workflow configuration to trigger the backport action
when a user writes a `/backport` comment on a pull request.
The bot itself restricts that only merged pull requests can be
backported.
This allows to backport pull requests that have already been merged.
Just add the backport labels to the merged PR and write `/backport`.
> WARNING! The bot will try to backport to the branches of all backport labels.
> Previously created backport pull requests are not taken into account.
> New pull requests will be created for each label.
> Add on-comment trigger to backport action workflow

- .github/workflows/backport.yml
The backport was running unconditionally after #341. It might be that the expression syntax is the cause of this.
> ci(github): fix backport conditions

- processes/actionRunner.bpmn
- processes/chaosExperiment.bpmn
- processes/chaosToolkit.bpmn
Add more context to the failure messages. The timeout is set as variable
such we can use it inside our failure report. Furthermore the cluster
name and cluster id is added to the report.
```json
{
"startTime": 1621240328000,
"testResult": "FAILED",
"failureCount": 1,
"endTime": 1621241229000,
"failureMessages": [
" Action with name: 'All pods should be ready' timed out after PT900S.",
" Chaos experiment 'Zeebe deployment distribution' failed.",
" Experiment failed for cluster plan: 'Production - M' against cluster 'Cluster Under Test' (c0ba034d-b433-4f99-a1ff-68a20bd9f0f1)."
]
}
```
> Add more details to failure msgs

- docs/operator-handbook.md
- testbench-dev.yaml
- testbench-prod.yaml
The old URL was from a time when the API was still being developed.
This now has an official URL, this URL is also whitelisted by the firewall, the old URL is not.
This also reformatted one of the markdown files.
> fix cloud API url

- core/chaos-workers/chaos-worker/src/main/kotlin/io/zeebe/chaos/chaosMain.kt
The sub process was previous not terminated after the time was up. This destroys the created sub process after timeout
> Destroy sub process

- core/chaos-workers/chaos-worker/src/main/kotlin/io/zeebe/chaos/chaosMain.kt
Destroy the created sub process after timeout
Backport https://github.com/zeebe-io/zeebe-cluster-testbench/pull/358
> [Backport 0.26] Destroy sub process

- core/chaos-workers/chaos-worker/pom.xml
- core/chaos-workers/chaos-worker/src/main/kotlin/io/zeebe/chaos/AwaitMessageCorrelationHandler.kt
- core/chaos-workers/chaos-worker/src/main/kotlin/io/zeebe/chaos/AwaitProcessWithResultHandler.kt
- core/chaos-workers/chaos-worker/src/main/kotlin/io/zeebe/chaos/DeployMultipleVersionsHandler.kt
- core/chaos-workers/chaos-worker/src/main/kotlin/io/zeebe/chaos/chaosMain.kt
- core/chaos-workers/chaos-worker/src/main/resources/log4j2.xml
1. In order to log via json layout, which is better visible and processed
by stackdriver, this commits adds a dependency to the zeebe-util module
and uses the StackDriverLayout
2. Use MDC for logging, add as context information:
* the job type
* cluster id
* cluster plan
* process instance id
3. Furthermore the process logs are redirected to log4j and uses the
correct context
Example output:
```
{"severity":"DEBUG","logging.googleapis.com/sourceLocation":{"function":"invoke","file":"chaosMain.kt","line":159},"message":"+ kubectl wait --for=condition=Ready pod -l app.kubernetes.io/app=zeebe --timeout=900s -n 0ee5902e-1dfa-4805-9eb2-51d8036faaa2-zeebe","serviceContext":{"service":"chaos-worker","version":"development"},"context":{"clusterPlan":"Production - …
```
> Improve chaos logging

- core/chaos-workers/Dockerfile
- core/chaos-workers/chaos-worker/pom.xml
In order to fix our Log4J issue, which was caused by the assembly plugin
and building a jar with dependencies, we need to replace the assembly
plugin with the shade plugin and use a third-party plugin to make sure
that the log4j plugin dat file is correctly merged with all
dependencies.
This makes it possible to have the strackdriver logging and building a
jar with dependencies.
Found it via https://stackoverflow.com/questions/25065580/log4j2-custom-plugins-annotation-processing-with-maven-assembly-plugin and https://maven.apache.org/plugins/maven-shade-plugin/examples/executable-jar.html
> fix(chaos): replace assembly with shade plugin

- core/chaos-workers/Dockerfile
- core/chaos-workers/chaos-worker/pom.xml
- pom.xml
In order to reference the jar with dependencies this commit gives it a
unique name without artifact or version, which is used in the Dockerfile
as well
Refactored the chaos worker pom a bit:
* Introduce version properties and migrated to newer version
* Small clean up of pom (remove unused plugins)
> Fix docker build

- core/chaos-workers/chaos-worker/src/main/kotlin/io/zeebe/chaos/chaosMain.kt
Previously the output streams have been printed after another, which can
cause confusion and makes it not really visible what is happening.
Furthermore the worker thread was blocked, until the process was done.
This cause problems on handling jobs, not terminating the process after
some time and we are not seeing what is going on.
For more information read https://github.com/zeebe-io/zeebe-cluster-testbench/issues/368
closes https://github.com/zeebe-io/zeebe-cluster-testbench/issues/368
Sorry with bothering you all the time @pihme
> fix(chaos): print system error together with system out

- core/chaos-workers/Dockerfile
- core/chaos-workers/chaos-worker/pom.xml
- core/chaos-workers/chaos-worker/src/main/kotlin/io/zeebe/chaos/chaosMain.kt
- pom.xml
Backports several chaos worker fixes to align the chaos worker with 1.0 and make it possible to use the stackdriver logging also on 0.26.
Backport https://github.com/zeebe-io/zeebe-cluster-testbench/pull/365
Backport https://github.com/zeebe-io/zeebe-cluster-testbench/pull/366
Backport https://github.com/zeebe-io/zeebe-cluster-testbench/pull/369
Backport https://github.com/zeebe-io/zeebe-cluster-testbench/commit/6ead6e0858833085b43e05c98923ba5dc407f312
closes https://github.com/zeebe-io/zeebe-cluster-testbench/issues/370
> [Backport 0.26] Backport several chaos worker fixes 

- core/chaos-workers/chaos-worker/src/main/kotlin/io/zeebe/chaos/DeployMultipleVersionsHandler.kt
It could happen that deployment of the initial version of the
multiVersion process would fail. The handler awaits deployment of the
successive versions and in the end expects that 10 different versions
were deployed, but this could be lower if one of the model_v1
deployments failed.
By reworking the multi version deployment to a collection pipeline, it becomes much more clear 
what happens and when things go wrong. This also allows us to respond to failure cases.
The job can be failed (keeping retries the same) when multi version deployment fails.
This failure should not affect the standard timer boundary event that times out if the task is not 
completed on time (in actionRunner.bpmn).
> Improve multi version deploy

- core/chaos-workers/chaos-worker/pom.xml
- core/chaos-workers/chaos-worker/src/main/kotlin/io/zeebe/chaos/DeployMultipleVersionsHandler.kt
- pom.xml
Backports #389 to `stable/0.26`
I needed to add awaitility as a dependency. 
Some of the commits could be directly cherry-picked, those have the [cherry-picked from ..] footer in the commit message, but I also had to move some code around to resolve conflicts, those do not have the [cherry-picked from ..] footer.
> Backport 389 to stable/0.26

- cloud-client/src/main/java/io/zeebe/clustertestbench/cloud/CloudAPIClientFactory.java
- cloud-client/src/main/java/io/zeebe/clustertestbench/cloud/filter/EntityLoggingFilter.java
- core/src/main/java/io/zeebe/clustertestbench/handler/GatherInformationAboutClusterInCamundaCloudHandler.java
- core/src/main/resources/log4j2.xml
It is not always clear what is returned by the cloudAPI. Let's print out
the results at debug level to make it easier to debug when things have
changed.
Specifically, this might help to find out why the operate url is null.
relates to #380
> Log received cluster info

- cloud-client/src/main/java/io/zeebe/clustertestbench/cloud/response/ClusterInfo.java
Fixes an incident where the current status of a cluster cannot be queried.
The links property of clusterinfo did not allow any unknown fields, but `zeebeAuthority` has been added.
This PR fixes this by marking the links with the `JsonIgnoreProperties` annotation.
> Allow unknown properties in responded links

- cloud-client/src/main/java/io/zeebe/clustertestbench/cloud/filter/EntityLoggingFilter.java
- core/src/main/java/io/zeebe/clustertestbench/bootstrap/Launcher.java
- core/src/main/java/io/zeebe/clustertestbench/handler/CreateApiClientInCamundaCloudHandler.java
- core/src/main/java/io/zeebe/clustertestbench/handler/CreateClusterInCamundaCloudHandler.java
- processes/prepare-zeebe-cluster-in-camunda-cloud.bpmn
- processes/run-test-in-camunda-cloud.bpmn
Adds a workaround to the missing region in the zeebe address url.
It splits the client creation from the cluster creation. This means the cluster is not deleted everytime something goes wrong in the client creation part. 
It also adds a short delay between the client creation and the connection info retrieval, so that console has time to be updated.
The workaround can be removed when camunda-cloud/console#2225 is resolved
> Fix cluster creation

- Jenkinsfile
We want to disable the 0.26 testbench auto deployment as this version is no longer
supported. This commit disables the branch name deploy trigger in order
to avoid any accidental redeployments. Manual deployments are still possible
related to #423
> chore(ci): disable deploy step

- processes/qa-protocol.bpmn
The cluster plans that were tested were based on the T-shirt sizes defined pre GA.
All new customers will be able to create clusters in a GA cluster plan which matches what Production - S was.
Therefore, we want to test this cluster plan exclusively.
> chore(processes): focus on testing Production - S exclusively

- cloud-client/src/main/java/io/zeebe/clustertestbench/cloud/response/ParametersResponse.java
- core/src/main/java/io/zeebe/clustertestbench/handler/MapNamesToUUIDsHandler.java
- core/src/test/java/io/zeebe/clustertestbench/handler/MapNamesToUUIDHandlerTest.java
Cluster plan name is not unique; it is unique only with in a region. This commit uses the region info when looking up for cluster plan names. So when there are cluster plans with same name in different regions, it will map to the correct one.
closes #211
> fix(core): filter for region when looking up for cluster plan

- core/src/main/java/io/zeebe/clustertestbench/handler/DeleteClusterInCamundaCloudHandler.java
The change adds a check whether the cluster still exists before it is deleted.
closes #223
> Check whether cluster still exists

- core/chaos-workers/chaos-worker/src/main/kotlin/io/zeebe/chaos/chaosMain.kt
* redirecting the error stream to avoid getting stuck if it is written to the error stream
* setting a timeout to make it more visible if the process is stuck
> fix(chaos): avoid getting stuck on run command

- .ci/scripts/deploy.sh
**Key feature:** Everything is bundled in the image and jar, which means we can now change zeebe-chaos master without causing issues.
Release 1.2.0 https://github.com/zeebe-io/zeebe-chaos/releases/tag/1.2.0
Release 1.1.0 https://github.com/zeebe-io/zeebe-chaos/releases/tag/1.1.0
Note: Ideally we could update the used version via dependabot but this is currently not supported.
> ci: update zeebe-chaos

- core/chaos-workers/deployment/chaosWorker-prod.yaml
- testbench-prod.yaml
I created a new cluster in our `Just testbench` org, a new Zeebe cluster api client and a new cluster api client. I updated the keys in Vault and this PR will update the client id's
related to https://github.com/zeebe-io/zeebe-cluster-testbench/issues/533
> ci: adjust client id's for Testbench Prod

- .ci/scripts/deploy.sh
Waiting for condition ready does not work if there are pods that are shut down.
Since we are restarting a rollout before, we can just wait for the rollout to complete
> fix: finish deploy when there are shutdown pods

- core/pom.xml
The Providers file located in META-INF/services is supposed to define
the available provider classes. This is where it will look for the
writers. It seemed that the shade plugin somehow merged these files
differently. By defining an appending strategy the file should contain
all entries.
This was an idea from: https://stackoverflow.com/a/18538803/3442860
Note that we use newer version that is not in the javax.ws.rs but in
jakarta.ws.rs namespace.
closes #608
> Fix jakarta.ws.rs.ext.Providers file in shaded jar

- core/pom.xml
- pom.xml
Fix for the failing PR by dependabot #606 
The dependency we use here has been replaced with a different group and artifact id. Making sure we stay up to date I have changed them and switched to the latest version.
Logging still works fine as can be seen here: https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0Aresource.labels.project_id%3D%22zeebe-io%22%0Aresource.labels.location%3D%22europe-west1-b%22%0Aresource.labels.cluster_name%3D%22zeebe-cluster%22%0Aresource.labels.namespace_name%3D%22testbench-1-x-dev%22%0Alabels.k8s-pod%2Fapp%3D%22testbench%22%0A%0A;timeRange=2022-03-25T08:28:15.834Z%2F2022-03-25T09:18:15.834448Z;cursorTimestamp=2022-03-25T08:49:46.584Z?project=zeebe-io
The jsonPayload gets added and filled with the correct fields.
> Log4j maven shade plugin extension

- .gitignore
- pom.xml
Introduces the `flatten-maven-plugin` in the build process. The projects are flattened according to the `ossrh` rules.
I took a shortcut with the description, by setting it to the name of the module. Before we didn't have any descriptions at all and this would take preference over the description that we would otherwise inherit from the `camunda-release-parent` pom.
closes #580
> feat: flatten all POMs for deployment

- .mvn/jvm.config
Copy and paste of https://github.com/camunda/zeebe/pull/8130 
> Adding add-opens is a workaround for [OSSRH-66257](https://issues.sonatype.org/browse/OSSRH-66257) and [NEXUS-26993](https://issues.sonatype.org/browse/NEXUS-26993). Because we don't control the plugin ourselves and instead inherit it from camunda-release-parent we can't just add a dependency overwrite
as suggested in [OSSRH-66257](https://issues.sonatype.org/browse/OSSRH-66257).
> ci: open java modules for nexus-staging-maven-plugin

- core/src/main/java/io/zeebe/clustertestbench/handler/TriggerMessageStartEventHandler.java
- core/src/test/java/io/zeebe/clustertestbench/handler/TriggerMessageStartEventHandlerTest.java
Allows multiple concurrent invocations of the triggered process by using an empty correlation key.
closes #630
> Allow multiple concurrent invocations

- Jenkinsfile
- docs/developer-handbook.md
we are restructuring Vault paths to ease the self-service.
See announcement on [slack](https://camunda.slack.com/archives/C03AEFWGJ9K/p1657524606321389).
The secrets have already been copied to the new space and the team was granted permission.
> chore(ci): adjust direct Vault usage in Jenkins to new path

- pom.xml
Bumps the google-java-format plugin used by spotless to 1.15.0.
This should avoid the following error when running `mvn compile`
>[ERROR] Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.28.0:apply (default) on project zeebe-cluster-testbench-core: Execution default of goal com.diffplug.spotless:spotless-maven-plugin:2.28.0:apply failed: java.lang.Exception: You are not using latest version on JVM 11+.
[ERROR] Try to upgrade to google-java-format 1.15.0, which may have fixed this problem.: InvocationTargetException: 'long com.sun.tools.javac.tree.DCTree$DCReference.getSourcePosition(com.sun.tools.javac.tree.DCTree$DCDocComment)'
> deps(maven): bump google-java-format to 1.15.0

- cloud-client/pom.xml
- cloud-client/src/test/java/io/zeebe/clustertestbench/cloud/CloudAPIClientTest.java
- cloud-client/src/test/java/io/zeebe/clustertestbench/cloud/JsonAssertions.java
- cloud-client/src/test/java/io/zeebe/clustertestbench/cloud/oauth/OAuthClientTest.java
- core/pom.xml
- integration-tests/pom.xml
- internal-cloud-client/pom.xml
- pom.xml
- testdriver/api/pom.xml
- testdriver/api/src/test/java/io/zeebe/clustertestbench/testdriver/api/JsonAssertions.java
- testdriver/api/src/test/java/io/zeebe/clustertestbench/testdriver/api/TestReportTest.java
- testdriver/sequential/pom.xml
This cleans up the pom files:
- improves the readability by applying a consistent style
- moves all version definitions into dependency management and plugin management
- moves all properties into the root project
- organizes dependencies into a few main categories
- ~re-enables the maven enforcer plugin, reduces the strictness from `dependencyConvergence` to `requireUpperBoundDeps`~
- removes unnecessary dependencies on `zeebe-util` and `zeebe-test-util` modules
This pull request had been on hold since it was first opened in March 2022. This was at the time that ZPT hadn't been officially released yet, and this project depended on a SNAPSHOT version of it. Dependency convergence between ZPT and the Zeebe Client was a major reason that I was unable to re-enable the maven enforcer plugin. …
> Maven pom spring cleaning

- Jenkinsfile
This addresses a new safety check that currently leads to a failing release.
See similar fix to other Jenkins setup [here](https://github.com/camunda/camunda-optimize/commit/8e76b89f3272a1dd5144ed200a84c63ba54c1a19).
> fix(ci): add git safe directory for release

- workflows/qa-github-trigger.bpmn
Use a non-interrupting boundary timer event instead of an interrupting one to ensure that incidents in the called process remain visible in Operate.
> fix: don't hide incident when QA times out

- cloud-client/src/main/java/io/zeebe/clustertestbench/cloud/CloudAPIClient.java
- cloud-client/src/test/java/io/zeebe/clustertestbench/cloud/CloudAPIClientTest.java
Previously permission were ignored. But now the api expects Zeebe with caps Z.
https://camunda.slack.com/archives/CKZK2E7RP/p1680265285860139?thread_ts=1680264644.312409&cid=CKZK2E7RP 
https://github.com/camunda-cloud/camunda-cloud-management-apps/pull/160
> fix: use correct permission string

- processes/qa-protocol.bpmn
The region name has changed:
- from `Belgium, Europe (europe-west1) aka. new chaos`
- to `Belgium, Europe (europe-west1)`
> fix(processes): rename used region for QA runs

- .github/workflows/build.yml
- The `ZCTB_SLACK_WEBHOOK_URL` env var is an empty string
- The var is required, but empty string is accepted
- This env var is filled from a k8s secret, other secrets are correctly filled in
- The k8s secret is also an empty string
- The deploy.sh script is run from build.yml workflow but does not pass in the url as secret (even though the secret is retrieved in the import secrets step)
> Add slack webhook url as environment variable

- core/src/main/java/io/zeebe/clustertestbench/handler/CreateGenerationInCamundaCloudHandler.java
- core/src/test/java/io/zeebe/clustertestbench/handler/CreateGenerationInCamundaCloudHandlerTest.java
- external-console-api-client/src/main/java/io/zeebe/clustertestbench/internal/cloud/ExternalConsoleAPIClient.java
- external-console-api-client/src/test/java/io/zeebe/clustertestbench/internal/cloud/StubExternalConsoleAPIClient.java
> [!Note]
> This a shortcut fix or workaround until https://github.com/camunda-cloud/camunda-cloud-management-apps/issues/1731 is fixed.
Normally we would expect that we can clone all kinds of generations but currently, this is not possible. If we reference a generation without the upgradeable from reference (so no reference) we retrieve errors (not found generation) which are hard to debug. See related issue https://github.com/zeebe-io/zeebe-cluster-testbench/issues/945
closes #945
> Handle invalid generations

- .ci/scripts/deploy.sh
- .github/workflows/build.yml
Recently I removed old services accounts from our IAM, see https://app.slack.com/client/T0PM0P1SA/C064CNSFKFF
This caused to fail the builts/deployments for testbench.
This PR migrates the old Jenkins service account JSON usage to the official workload identity federation usage, [which is recommended by Google](https://github.com/google-github-actions/auth?tab=readme-ov-file#workload-identity-federation-through-a-service-account).
I have set up a new service account and created a new workload identity pool, etc. Since I know had to do this multiple times already I wrote a script, which we can reuse the next time
```sh
#!/bin/bash
gcloud components update
name="testbench"
detailedName="ZBTestbench"
org=zeebe-io
repo=zeebe-io/zeebe-cluster-testbench
export PROJECT_ID="zeebe-io"
gcloud iam …
```
> ci: migrate to workload federation

- .github/workflows/build.yml
- .github/workflows/release.yml
It's unclear to me why these jobs specify a specific maven version. It's not managed by any version manager, so it quickly gets out of date.
It was introduced with https://github.com/zeebe-io/zeebe-cluster-testbench/pull/802
Instead, it's fine to use the latest maven version for our CI. This is needed because the flatten maven plugin v1.6 requires a newer maven version then the one we currently specify in our CI.
This will help us merge:
- https://github.com/zeebe-io/zeebe-cluster-testbench/pull/977
> ci: dont specify specific maven version

- .idea/codeStyles/Project.xml
- core/src/main/java/io/zeebe/clustertestbench/handler/CreateGenerationInCamundaCloudHandler.java
- core/src/test/java/io/zeebe/clustertestbench/handler/CreateGenerationInCamundaCloudHandlerTest.java
A bug in Camunda Cloud Console prevented cloning of generations that were not marked as upgradable from. The issue has been fixed and the guard clause needs to be removed from the testbench code.
closes #981
> refactor(core): remove guard clause for generation cloning

- core/src/main/java/io/zeebe/clustertestbench/bootstrap/Launcher.java
- core/src/main/java/io/zeebe/clustertestbench/handler/NotifyEngineersHandler.java
- core/src/test/java/io/zeebe/clustertestbench/bootstrap/ConvertUrlTest.java
- core/src/test/java/io/zeebe/clustertestbench/handler/NotifyEngineersHandlerTest.java
Adds some better formatting, improved wording (speaking of target cluster) on the failure messages and adds the Operate URL to easily navigate to the orchestration cluster.
I will keep improving this, like adding logs URL, etc. but will do this later.
Example message:
```
:bpmn-error-throw-event:
_processID_ on _CLUSTER_PLAN_B_ failed for branch .
Check out here: http://url/clusterId
*Details:*
* Zeebe image: _ZEEBE:VERSION_
* Generation: _GENERATION_C_
* Target cluster : _CLUSTER_A_
* Target cluster Operate: https://localhost.test/
* Business key: http://jenkins/branch/build
*Failures:*
Failure count: 1
Error message 1
Error message 2
```
> Improve failure messages

- core/src/main/java/io/zeebe/clustertestbench/handler/NotifyEngineersHandler.java
- core/src/test/java/io/zeebe/clustertestbench/handler/NotifyEngineersHandlerTest.java
When failing chaos experiments we have a long way to find the right logs, especially if we want to look at the zbchaos logs, as this is not linked.
With this PR we close the gap and have a direct connection to the running pods logs
> feat: add zbchaos console log url

- processes/qa-github-trigger.bpmn
This PR reduces the complexity of our process models (by factor 5) and need of tests clusters by 50%.
We have one abstraction/call-activity layer:
**Before:**
The QA trigger process model was quite abstract, and going to find the right chaos orchestration was several layers hidden behind call activities.
We needed 5+ process models to reach the actual orchestraction of chaos experiments.
QA-Github-trigger
QA-protocol
run-all-tests-in-camunda-cloud-per-cluster-plan
run-all-tests-in-camunda-cloud
run-test-in-camunda-cloud
**Details:**
This PR should reduce the indirection and clean up some unnecessary abstractions.
- Removed/inlined several call activities that had no real use.
- For example, the process run all tests (the name itself was confusing as it shared the prefix with another one), …
> Reduce indirection for QA trigger

- .github/workflows/build.yml
- bors.toml
Related to https://github.com/camunda/team-infrastructure/issues/633 and the removal of Bors instances.
This PR removes the `bors.toml` file, which is no longer used.
> chore: remove bors.toml config file
