zeebe-io/zeebe-cluster-testbench

- .ci/podSpecs/distribution.yml
- Jenkinsfile
closes #8
This implements a part of #8, namely the pushing of Docker images
> add docker agent and push images to docker

- .ci/podSpecs/distribution.yml
- .ci/scripts/deploy.sh
- .ci/scripts/prepare-deploy.sh
- Jenkinsfile
- README.md
- docs/operator-handbook.md
Enables automatic deployment of changes to master
> chore(ci): add deploy scripts

- testdriver/api/pom.xml
- testdriver/api/src/main/java/io/zeebe/clustertestbench/testdriver/impl/TestTimingContext.java
- testdriver/api/src/test/java/io/zeebe/clustertestbench/testdriver/impl/TestTimingContextTest.java
- testdriver/sequential/src/main/java/io/zeebe/clustertestbench/testdriver/sequential/SequentialTestDriver.java
> feat(sequential-test): correlate iterations to workflow ids

- testdriver/api/src/main/java/io/zeebe/clustertestbench/testdriver/impl/TestTimingContext.java
- testdriver/api/src/test/java/io/zeebe/clustertestbench/testdriver/impl/TestTimingContextTest.java
- testdriver/sequential/src/main/java/io/zeebe/clustertestbench/testdriver/sequential/SequentialTestDriver.java
> feat(sequential-test): add start time to workflow instance

- README.md
- core/src/main/java/io/zeebe/clustertestbench/worker/NotifyEngineersWorker.java
> feat(sequential-test): add operate url to slack info

- core/src/main/java/io/zeebe/clustertestbench/worker/NotifyEngineersWorker.java
> feat(sequential-test): add summary of test failures to Slack notification

- testdriver/sequential/src/main/java/io/zeebe/clustertestbench/testdriver/sequential/SequentialTestDriver.java
> fix(sequential-test): Add iteration to exception error message

- workflows/daily-test-protocol.bpmn
- workflows/run-all-tests-in-camunda-cloud-per-cluster-plan.bpmn
> fix(workflows): block unwanted variable propagation

- testdriver/sequential/pom.xml
- testdriver/sequential/src/main/java/io/zeebe/clustertestbench/testdriver/sequential/ExceptionFilterBuilder.java
- testdriver/sequential/src/main/java/io/zeebe/clustertestbench/testdriver/sequential/SequentialTestDriver.java
- testdriver/sequential/src/test/java/io/zeebe/clustertestbench/testdriver/sequential/ExceptionFilterBuilderTest.java
> 47 tolerance for incomplete deployment

- Jenkinsfile
> chore(ci): send notify to slack on master build failure

- README.md
- workflows/qa-protocol.bpmn
> fix(workflows): add missing variable to workflow

- .ci/scripts/deploy.sh
- Jenkinsfile
> chore(ci): wait for pods to start, fail build on timeout

- core/chaos-workers/Dockerfile
- core/chaos-workers/handleJob.sh
- core/chaos-workers/handleJobTest.sh
- core/chaos-workers/ioHandlerUtil.sh
Input extraction is moved into separate util script, which is then also used later for output creating.
Util script is imported by handler. Tests are written against util functions
closes https://github.com/zeebe-io/zeebe-cluster-testbench/issues/105
> chore(chaos): extract io mapping to util script

- core/pom.xml
- core/src/main/java/io/zeebe/clustertestbench/bootstrap/Launcher.java
- core/src/main/java/io/zeebe/clustertestbench/handler/CreateClusterInCamundaCloudHandler.java
- core/src/main/java/io/zeebe/clustertestbench/handler/CreateGenerationInCamundaCloudHandler.java
- core/src/main/java/io/zeebe/clustertestbench/handler/MapNamesToUUIDsHandler.java
- core/src/main/java/io/zeebe/clustertestbench/util/RandomNameGenerator.java
- core/src/main/java/io/zeebe/clustertestbench/util/StringLookup.java
- core/src/test/java/io/zeebe/clustertestbench/handler/CreateGenerationInCamundaCloudHandlerTest.java
- core/src/test/java/io/zeebe/clustertestbench/util/StringLookupTest.java
- pom.xml
> feat(core): improve error message when items cannot be found

- core/chaos-workers/handleJobTest.sh
- core/chaos-workers/handlerUtil.sh
Build correct testResult json with chaos experiment name as content
closes https://github.com/zeebe-io/zeebe-cluster-testbench/issues/88
> chore(chaos): complete job with fail message

- core/chaos-workers/handleJob.sh
- core/chaos-workers/handleJobTest.sh
- core/chaos-workers/handlerUtil.sh
- testdriver/api/src/main/java/io/zeebe/clustertestbench/testdriver/api/TestReport.java
Turned out that previous we only executed the first experiment. :-1: 
This PR fixes this problem and adds more output to the job completion, which shows which experiments have been executed successfully. Added new unit tests for that.
Furthermore as suggested if experiments are skipped I also added a new output and test result. Might need to adjust also the java code, but not 100% sure whether this is necessary, since we only check the result via FEEL and check whether is has failed.
> Run all given experiments

- workflows/run-test-in-camunda-cloud.bpmn
* Renames _Run Sequential Test in Camunda Cloud" to "Run Test in Camunda Cloud"
closes #136
> fix(workflows): rename workflow which is now more general

- scripts/runTestForId
Adds helper script to trigger daily run. Happy discuss the name.
> chore(scripts): add new helper script

- README.md
- core/src/main/java/io/zeebe/clustertestbench/handler/RecordTestResultHandler.java
Adds a column to the test report that shows which test was run.
closes #124
> feat(core): add column to display test workflow in test report

- Jenkinsfile
Changes the Jenkinsfile to notify Slack whenever the build result changes.
> chore(ci): notify slack when build result changes

- README.md
- docs/developer-handbook.md
Adds developer handbook
Depends in part on #161
> chore(docs): add developer handbook

- scripts/chaos-log-chunker.sh
Not proud of it. But took me enough time to find these lines, so I better want to share it.
> chore(scripts): add script to help a little bit with working with chaos test logs

- docs/developer-handbook.md
- pom.xml
adds permutation testing capabilities
> chore(maven): add permutation testing

- core/src/main/java/io/zeebe/clustertestbench/handler/NotifyEngineersHandler.java
- core/src/main/java/io/zeebe/clustertestbench/handler/RecordTestResultHandler.java
- core/src/test/java/io/zeebe/clustertestbench/handler/NotifyEngineersHandlerTest.java
closes #187 
* adds the _businessKey_ field to Google Sheet of test reports and Slack message
* the business key for workflows triggered by Jenkins is the URL to the Jenkins build
* the business key for daily tests is empty
> feat(core): add businessKey to Google Sheet and Slack message

- .ci/podSpecs/distribution.yml
> chore(ci): specify image version

- Jenkinsfile
> Fix deploy

- .github/workflows/backport.yml
It is possible to define an expression over multiple lines using yaml folding: https://stackoverflow.com/a/67532120/3442860
> Restyle backport.yml to multiline if

- docs/developer-handbook.md
Adds a description about multi-version support to the developer-handbook.
closes #251
> docs(dev): describe multi version support

- testbench-dev.yaml
- testbench.yaml
backport of similar change to develop
> fix cloud API url

- core/chaos-workers/chaos-worker/pom.xml
- core/chaos-workers/chaos-worker/src/main/kotlin/io/zeebe/chaos/AwaitProcessWithResultHandler.kt
- core/chaos-workers/chaos-worker/src/main/kotlin/io/zeebe/chaos/DeployMultipleVersionsHandler.kt
- core/chaos-workers/chaos-worker/src/main/kotlin/io/zeebe/chaos/chaosMain.kt
- Also extract reusable methods in abstract class
- Also activate Idea Kotlin code conventions
- removed redundant semicolons
> refactor(chaos): migrate "await-processes-with-result.sh" to Kotlin

- workflows/actionRunner.bpmn
- workflows/chaosExperiment.bpmn
- workflows/chaosToolkit.bpmn
Backports https://github.com/zeebe-io/zeebe-cluster-testbench/pull/353
> [Backport 0.26]  Add more details to failure msgs

- core/chaos-workers/chaos-worker/src/main/kotlin/io/zeebe/chaos/AwaitMessageCorrelationHandler.kt
- core/chaos-workers/chaos-worker/src/main/kotlin/io/zeebe/chaos/chaosMain.kt
migrate await-message-correlation.sh to Kotlin
> feat(chaos): migrate await-message-correlation.sh to Kotlin

- core/chaos-workers/chaos-worker/src/main/kotlin/io/zeebe/chaos/AwaitMessageCorrelationHandler.kt
- core/chaos-workers/chaos-worker/src/main/kotlin/io/zeebe/chaos/AwaitProcessWithResultHandler.kt
- core/chaos-workers/chaos-worker/src/main/kotlin/io/zeebe/chaos/chaosMain.kt
- also fix timeout and set default poll interval in chaosMain.kt
- also removed redundant semicolons
> fix(chaos): fix workflow in AwaitMessageCorrelationHandler

- core/chaos-workers/chaos-worker/pom.xml
- core/chaos-workers/chaos-worker/src/main/kotlin/io/zeebe/chaos/DeployMultipleVersionsHandler.kt
- core/chaos-workers/chaos-worker/src/main/kotlin/io/zeebe/chaos/chaosMain.kt
- core/chaos-workers/chaos-worker/src/main/resources/log4j2.xml
> Backport chaos log improvements

- core/pom.xml
- core/src/test/java/io/zeebe/clustertestbench/handler/AggregateTestResultHandlerTest.java
- core/src/test/java/io/zeebe/clustertestbench/handler/CheckGenerationUsageHandlerTest.java
- core/src/test/java/io/zeebe/clustertestbench/handler/CreateGenerationInCamundaCloudHandlerTest.java
- core/src/test/java/io/zeebe/clustertestbench/handler/DeleteGenerationInCamundaCloudHandlerTest.java
- core/src/test/java/io/zeebe/clustertestbench/handler/NotifyEngineersHandlerTest.java
- core/src/test/java/io/zeebe/clustertestbench/handler/TriggerMessageStartEventHandlerTest.java
- pom.xml
This changes the tests for workers to use the stubs of the https://github.com/camunda-community-hub/zeebe-worker-java-testutils instead of Mocks
> Use worker testutils

- .github/dependabot.yml
- docs/developer-handbook.md
* Removes 0.26 from dependabot scans
* Updates documentation
closes #423
> Disable 0 26

- core/chaos-workers/deployment/chaosWorker-dev.yaml
- testbench-dev.yaml
related to https://github.com/zeebe-io/zeebe-cluster-testbench/issues/533
> ci: update testbench dev deployment

- core/src/main/java/io/zeebe/clustertestbench/handler/TriggerMessageStartEventHandler.java
- integration-tests/pom.xml
- integration-tests/src/test/java/io/zeebe/clustertestbench/it/handler/TriggerMessageStartEventHandlerIT.java
- pom.xml
- testdriver/sequential/src/main/java/io/zeebe/clustertestbench/testdriver/sequential/SequentialTestDriver.java
- remove dependency to BPMN Spec
- rewrite test to use zeebe-process-test
> chore(it): refactor test to use zeebe-process-test instead of

- .ci/podSpecs/distribution.yml
- .ci/scripts/distribution/prepare.sh
- .github/workflows/codeql.yml
- Dockerfile
- cloud-client/pom.xml
- core/pom.xml
- integration-tests/pom.xml
- integration-tests/src/test/java/io/zeebe/clustertestbench/it/handler/TriggerMessageStartEventHandlerIT.java
- internal-cloud-client/pom.xml
- lgtm.yml
- pom.xml
- testdriver/api/pom.xml
- testdriver/sequential/pom.xml
> Upgrade to Java 17 & Use In-Memory Engine for tests

- pom.xml
> chore(maven): migrate to new artifacts.camunda.com

- core/src/main/java/io/zeebe/clustertestbench/handler/NotifyEngineersHandler.java
- core/src/test/java/io/zeebe/clustertestbench/handler/NotifyEngineersHandlerTest.java
> feat: add zeebe version to failure notification

- core/src/main/java/io/zeebe/clustertestbench/handler/CreateGenerationInCamundaCloudHandler.java
- core/src/test/java/io/zeebe/clustertestbench/handler/CreateGenerationInCamundaCloudHandlerTest.java
- internal-cloud-client/src/test/java/io/zeebe/clustertestbench/internal/cloud/StubInternalCloudAPIClient.java
* Make property `zeebeImage` optional
* Add additional properties `operateImage`, `optimizeImage`, and
`tasklistImage`
closes #657
> feat: additional properties to define the versions under test

- processes/qa-protocol.bpmn
- processes/run-all-tests-in-camunda-cloud.bpmn
Console changed the name of this region.
Because of this the process runs into incidents, as it cannot find the expected "new chaos" region.
> Change region from "new chaos" to "Belgium, Europe (europe-west1) aka. new chaos"

- core/src/main/java/io/zeebe/clustertestbench/handler/JobHandlerWithEnrichedLogger.java
- core/src/main/resources/log4j2.xml
Enable logging from zeebe clients, and add more logging for job handlers.
> Improve logging

- cloud-client/src/main/java/io/zeebe/clustertestbench/cloud/filter/EntityLoggingFilter.java
- external-console-api-client/src/main/java/io/zeebe/clustertestbench/internal/cloud/ExternalConsoleAPIClientFactory.java
- testbench-dev.yaml
Created a new dev cluster which can be used to test out features
> Use different dev cluster
